name: Build CPU Wheel

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: abetlen/llama-cpp-python
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt install -y libopenblas-dev
          pip install build

      - name: Build wheel
        run: python -m build --wheel
        env:
          CMAKE_ARGS: "-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cpu-latest
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
